Fixes #1096: Use podman instead of docker when building and testing containers. (#1095)
(cherry picked from commit 4201a1ac7df591993b0082d26fa6e801daab1634)

diff --git a/.github/workflows/image-manual.yml b/.github/workflows/image-manual.yml
--- a/.github/workflows/image-manual.yml
+++ b/.github/workflows/image-manual.yml
@@ -25,8 +25,8 @@ on:
         description: 'Qpid Proton source code url that returns a tar ball for a given branch'
         required: true
         default: 'http://github.com/apache/qpid-proton/archive/main.tar.gz'
-      dockerTag:
-        description: 'Docker tag to use for the skupper-router image'
+      containerTag:
+        description: 'Container tag to use for the skupper-router image'
         required: true
         default: 'custom'
       canPushLatestTag:
@@ -41,23 +41,23 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - run: |
-          # validate DOCKER_TAG
-          [[ ! "${DOCKER_TAG}" =~ ^[a-z0-9][a-z0-9.-]+[a-z0-9]$ ]] && echo "invalid tag - it must begin and end with letter or digit and contains - and ." && exit 1
+          # validate CONTAINER_TAG
+          [[ ! "${CONTAINER_TAG}" =~ ^[a-z0-9][a-z0-9.-]+[a-z0-9]$ ]] && echo "invalid tag - it must begin and end with letter or digit and contains - and ." && exit 1
           protected=(latest nightly master)
           for ptag in ${protected[@]}; do
-            if [[ "${ptag}" = "${DOCKER_TAG}" ]]; then
+            if [[ "${ptag}" = "${CONTAINER_TAG}" ]]; then
               echo "${ptag} cannot be used (protected tag)"
               exit 1
             fi
           done
         env:
-          DOCKER_TAG: '${{github.event.inputs.dockerTag}}'
+          CONTAINER_TAG: '${{github.event.inputs.containerTag}}'
       - uses: actions/checkout@v3
       - run: |
           # build, run tests and if all worked publish a custom image
-          export PROJECT_TAG="${DOCKER_TAG}"
+          export PROJECT_TAG="${CONTAINER_TAG}"
           # The version of skupper-router should be the same as the version of the image.
-          export VERSION="${DOCKER_TAG}"
+          export VERSION="${CONTAINER_TAG}"
           CAN_PUSH_LATEST='${{github.event.inputs.canPushLatestTag}}'
           if [ "${CAN_PUSH_LATEST}" == "true" ]; then
             echo 'image-manual.yml setting PUSH_LATEST=true, will push :latest tag'
@@ -67,7 +67,7 @@ jobs:
           fi
           ./.github/scripts/image.sh
         env:
-          DOCKER_USER: '${{ secrets.DOCKER_USER }}'
-          DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
+          CONTAINER_USER: '${{ secrets.DOCKER_USER }}'
+          CONTAINER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
           PROTON_SOURCE_URL: '${{github.event.inputs.protonSourceUrl}}'
-          DOCKER_TAG: '${{github.event.inputs.dockerTag}}'
+          CONTAINER_TAG: '${{github.event.inputs.containerTag}}'
